name: CI

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on:
      - ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check linting
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          args: -v -E gofmt -E gci --timeout 5m
